### ISSUE TITLE
So you wanna build a website?

### ISSUE THREAD

**Issue by jonathantneal** [csstools/postcss-preset-env-www#1]
Here’s the design in Figma: https://www.figma.com/file/UHiboJWhuaP8qJn0ipXntlrA/postcss-preset-env

Here’s a poorly CSS’d version of the homepage in CodePen: https://s.codepen.io/jonneal/debug/beede7dc0eb30ce7f019963e9da0f191

**Comment by yepninja** [comment]
Yep! I am ready to help to build a website :)

**Comment by Antonio-Laguna** [comment]
This is not forgotten and I think this is awesome! Saved Figma and will revisit
