### ISSUE TITLE
Incorrect nesting spec link

### ISSUE THREAD

**Issue by hacknug** [csstools/postcss-preset-env-www#13]
The current link for the nesting spec takes you to Tab Atkins's draft instead of CSSWG's. I can open a PR fixing this if someone can confirm this is the line that should change: https://github.com/csstools/postcss-preset-env-www/blob/master/views/cssdb.html#L1093

https://drafts.csswg.org/css-nesting-1/

**Comment by Antonio-Laguna** [comment]
@hacknug thanks for this and your patience! This is now tackled and fixed!
