### ISSUE TITLE
Source Code Pro is always rendered black on Firefox

### ISSUE THREAD

**Issue by d4rekanguok** [csstools/postcss-preset-env-www#14]
In Firefox (67), `Source Code Pro` is always rendered black:

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/3383539/56644893-923c8980-66b7-11e9-95c4-de49af79f495.png">

If I modify this rules...
```
font: 400 100%/1.5 var(--font-code); // --font-code = "Source Code Pro", monospace, monospace
```
To this
```
font: 400 100%/1.5 monospace; 
```
The color comes back:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/3383539/56645207-345c7180-66b8-11e9-86d4-efb637a9574a.png">

Works fine on Chrome & Safari.

**Comment by geoffp** [comment]
@jonathantneal I've followed the README in the master branch to get this fixed, but I have not been able to get the site working locally. Might there be a step or two missing?

**Comment by jm3** [comment]
FYI, this is still happening — issue should potentially be renamed, "source code samples are unreadable on Firefox"

**Comment by Antonio-Laguna** [comment]
@jm3 @geoffp @d4rekanguok  this should now have been fixed. Thanks for your patience!
