### ISSUE TITLE
Sidebar hides content on some screen sizes

### ISSUE THREAD

**Issue by Nicd** [csstools/postcss-preset-env-www#15]
When using the docs on certain screen sizes, the sidebar hides the content and cannot be collapsed. See the attached screenshot, it's from Firefox but it also reproduces at least on Vivaldi on macOS.

<img width="1114" alt="Screenshot 2019-06-12 at 11 01 51" src="https://user-images.githubusercontent.com/273137/59334027-48a90c00-8d02-11e9-990a-9f20892b8735.png">

**Comment by Antonio-Laguna** [comment]
This is now fixed on the latest version of this site!
