### ISSUE TITLE
Make logo a little longer to have a perfect cross

### ISSUE THREAD

**Issue by ai** [csstools/postcss-preset-env-www#16]
![Снимок экрана от 2022-01-23 01-13-22](https://user-images.githubusercontent.com/19343/150659639-6b3e90dc-46f3-458b-9114-a7ead7f73f11.png)

Right now a line between logo and Features link is too close to sidemenu line. We should move it to fit together. Or separated them.

**Comment by ai** [comment]
@Antonio-Laguna is it right repo for issues for website?

**Comment by Antonio-Laguna** [comment]
@ai nice catch! 

We'll be moving this soon into postcss-plugins monorepo since it makes sense from a maintenance perspective but won't be till we start with that milestone (probably in 2 weeks time)

**Comment by Antonio-Laguna** [comment]
@ai we've redeployed the site and this is moved to the monorepo. This issue should no longer exist! Thanks for reporting!
