### ISSUE TITLE
Site tightening

### ISSUE THREAD

**Issue by dbox** [csstools/postcss-preset-env-www#7]
Things I plan to take care of:

- [ ] Match top nav to comp: size, subtle border, hovers
- [ ] style dropdown
- [ ] responsive tweaks
- [ ] add `#` hover to jumplinks

q's for @jonathantneal : 
- [ ] Okay with bolder heading typography on lander?
- [ ] Okay to add [these guys](https://www.dropbox.com/s/1mpostw5qcg3n0v/Screenshot%202018-05-15%2009.41.52.png?dl=0_)?
- [ ] Should we change language in dropdown next stage 2 to say `Stage 2+ (Plugin default)`
- [ ] If not should we cookie user's choice?

**Comment by Antonio-Laguna** [comment]
@dbox thanks for opening this a while ago and I'm sorry this got overlooked. I've moved this to 

https://github.com/csstools/postcss-plugins/tree/main/sites/postcss-preset-env

If you still want to contribute ( we'd love it ) please reopen this there and we can discuss!
